baseurl = "https://qmstr.org/"
title = "The Quartermaster project."
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "qmstr"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-40601155-2"
# Define the number of posts per page
paginate = 10
# For Github pages?
canonifyurls = true

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

# [[menu.main]]
#     name = "FAQ"
#     identifier = "faq"
#     url  = "/faq/"
#     weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/orgs/QMSTR"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/fosscompliance"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Slack"
    url = "https://join.slack.com/t/qmstr/shared_invite/enQtMjYxNjUwNDIzNTcyLTcwNzQ4NzZhOTZiYTRjNzExMTUxM2VmN2I5MTRjMDM1OGY2ODBlODYxNDViMjMyNDBiODM0M2I2M2Q3OGQxN2U"
    pre = "<i class='fa fa-2x fa-slack'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "QMSTR"
    defaultKeywords = ["qmstr", "FOSS"]
    defaultDescription = "Read more..."

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Enable the contact form by entering your Formspree.io email
    email = "mirko@endocode.com"

    about_us = "<p>QMSTR creates an integrated Open Source toolchain that implements industry best practises of license compliance management. <a href=\"/pages/impressum\">Imprint</a></p>"
    copyright = "Copyright (c) 2017, Endocode. This web site is licensed under the AGPL."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>The Quartermaster Project</strong>
        <br>Endocode AG
        <br>Brückenstrasse 5a
        <br>10179 Berlin
        <br>Germany
      </p>
      """
      # latitude = "-12.043333"
      # longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false

[params.features]
    enable = true

[params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = "This is what our community says about Quartermaster."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "..."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Recent posts"
    subtitle = "Learn more about Quartermaster and FOSS Compliance tooling."
